#!/usr/bin/env node

/**
 * Interactive setup script for configuring Solana RPC endpoints
 * This script helps users create a properly configured .env.local file
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function main() {
  console.log('\n🚀 Solana Token Creator - RPC Endpoint Setup\n');
  console.log('This script will help you configure your Solana RPC endpoints.');
  console.log('Custom RPC endpoints are REQUIRED for mainnet to avoid 403 errors.\n');

  const envPath = path.join(__dirname, '..', '.env.local');
  const envExamplePath = path.join(__dirname, '..', '.env.example');

  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    console.log('⚠️  A .env.local file already exists.');
    const overwrite = await question('Do you want to overwrite it? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\nSetup cancelled. Your existing .env.local file was not modified.');
      rl.close();
      return;
    }
  }

  console.log('\n📝 Configuration Questions:\n');

  // Network selection
  console.log('1. Which network will you primarily use?');
  console.log('   - devnet: For testing (free, no RPC key needed)');
  console.log('   - mainnet-beta: For production (custom RPC endpoint REQUIRED)\n');
  
  const network = await question('Network (devnet/mainnet-beta) [devnet]: ');
  const selectedNetwork = network.trim() || 'devnet';

  let mainnetRpc = '';
  let devnetRpc = '';

  // RPC endpoint configuration
  if (selectedNetwork === 'mainnet-beta') {
    console.log('\n⚠️  IMPORTANT: You selected mainnet. You MUST configure a custom RPC endpoint.');
    console.log('\nGet a FREE RPC endpoint from:');
    console.log('  • Helius: https://helius.dev (Recommended)');
    console.log('  • QuickNode: https://quicknode.com');
    console.log('  • Alchemy: https://alchemy.com\n');
    
    mainnetRpc = await question('Enter your mainnet RPC URL: ');
    
    const configureDevnet = await question('\nDo you also want to configure a custom devnet RPC? (y/N): ');
    if (configureDevnet.toLowerCase() === 'y') {
      devnetRpc = await question('Enter your devnet RPC URL: ');
    }
  } else {
    console.log('\n✅ Using devnet. Public endpoints work fine for testing.');
    const configureCustom = await question('\nDo you want to configure a custom devnet RPC anyway? (y/N): ');
    if (configureCustom.toLowerCase() === 'y') {
      devnetRpc = await question('Enter your devnet RPC URL: ');
    }
  }

  // Backend URL
  console.log('\n2. Backend API URL for IPFS uploads:');
  console.log('   - Production: https://metabackend-c4e4.onrender.com');
  console.log('   - Local: http://0.0.0.0:10000\n');
  
  const backendUrl = await question('Backend URL [https://metabackend-c4e4.onrender.com]: ');
  const selectedBackend = backendUrl.trim() || 'https://metabackend-c4e4.onrender.com';

  // Generate .env.local content
  let envContent = `# Solana Token Creator - Environment Configuration
# Generated by setup script on ${new Date().toISOString()}
# ============================================
# DO NOT commit this file to version control
# ============================================

# Solana Network
NEXT_PUBLIC_SOLANA_NETWORK=${selectedNetwork}

`;

  if (mainnetRpc) {
    envContent += `# Custom Mainnet RPC Endpoint
NEXT_PUBLIC_SOLANA_RPC_MAINNET=${mainnetRpc}

`;
  } else {
    envContent += `# Custom Mainnet RPC Endpoint (REQUIRED for mainnet usage)
# Uncomment and add your RPC URL from Helius, QuickNode, or Alchemy:
# NEXT_PUBLIC_SOLANA_RPC_MAINNET=https://mainnet.helius-rpc.com/?api-key=YOUR_API_KEY

`;
  }

  if (devnetRpc) {
    envContent += `# Custom Devnet RPC Endpoint
NEXT_PUBLIC_SOLANA_RPC_DEVNET=${devnetRpc}

`;
  } else {
    envContent += `# Custom Devnet RPC Endpoint (optional, public endpoints work for testing)
# NEXT_PUBLIC_SOLANA_RPC_DEVNET=https://devnet.helius-rpc.com/?api-key=YOUR_API_KEY

`;
  }

  envContent += `# Backend API URL for IPFS uploads
NEXT_PUBLIC_BACKEND_URL=${selectedBackend}
`;

  // Write .env.local file
  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ Configuration complete!');
  console.log(`\n📄 Created: ${envPath}`);
  
  if (selectedNetwork === 'mainnet-beta' && !mainnetRpc) {
    console.log('\n⚠️  WARNING: You selected mainnet but did not configure a custom RPC endpoint.');
    console.log('You will see warnings and may experience 403 errors.');
    console.log('Please add your RPC endpoint to .env.local before using mainnet.');
  }

  console.log('\n🚀 Next steps:');
  console.log('   1. Review your .env.local file');
  if (selectedNetwork === 'mainnet-beta' && !mainnetRpc) {
    console.log('   2. Add your mainnet RPC endpoint to .env.local');
    console.log('   3. Restart your development server: npm run dev');
  } else {
    console.log('   2. Start your development server: npm run dev');
  }
  console.log('\n📚 For more information, see: RPC_CONFIGURATION.md\n');

  rl.close();
}

main().catch(err => {
  console.error('\n❌ Error:', err.message);
  rl.close();
  process.exit(1);
});
